### ISSUE TITLE
Setting SELF_URL_PATH to localhost breaks browser integration and PUSH

### ISSUE THREAD

**Issue by pschmitt** [clue/docker-ttrss#14]
I'd suggest removing [line 17 of the Dockerfile](https://github.com/clue/docker-ttrss/blob/master/Dockerfile#L17) and setting SELF_URL_PATH on runtime (ie. when the container is started) so that it can be either "guessed" by setting it to the container's hostname (`docker run -h HOSTNAME`) or directly set via an environment variable. Something like `TTRSS_URL` perhaps?

**Comment by clue** [comment]
Great suggestion! :+1: 

Imo we should add a `SELF_URL_PATH` `ENV` variable to our `Dockerfile` and apply its value during runtime in our `configure-db.php` script.

PRs very much appreciated! :)

**Comment by clue** [comment]
Closed via #15! Thanks!
